import { IMG } from "@/lib/images";

export type Category = "smash" | "dogs" | "notbeef" | "sides" | "shakes" | "brew";

export type MenuItem = {
  id: string;
  name: string;
  category: Category;
  /** Cents — money never lives in floats. */
  price: number;
  blurb: string;
  /** The build, bottom bun up. Rendered as the spec sheet. */
  build: string[];
  /** 0 (no heat) — 5 (send help). */
  heat: number;
  image?: string;
  badges?: string[];
  /** Griddle telemetry, printed on every card. */
  spec: { patties: number; ozEach: number; sear: string; temp: number };
};

export const CATEGORIES: { id: Category; label: string; note: string }[] = [
  { id: "smash", label: "Smash Burgers", note: "Never frozen. Smashed to order." },
  { id: "dogs", label: "Dogs & Brats", note: "Split, griddled, loaded." },
  { id: "notbeef", label: "Not Beef", note: "Same griddle. Different animal." },
  { id: "sides", label: "Tots & Fries", note: "Cheese sauce on the tots. Six sauces with the fries." },
  { id: "shakes", label: "Shakes", note: "Spun thick. Drink it with a spoon." },
  { id: "brew", label: "Brew", note: "Sixteen lines, rotating." },
];

export const MENU: MenuItem[] = [
  {
    id: "handcraft-double",
    name: "The Handcraft Double",
    category: "smash",
    price: 1395,
    blurb: "The one the whole block queues for. Two patties, lace-crisp at the edges.",
    build: [
      "Toasted brioche crown",
      "Handcraft sauce",
      "Shredded romaine",
      "Vine tomato",
      "Sharp American",
      "Smashed 3oz patty",
      "Sharp American",
      "Smashed 3oz patty",
      "Buttered heel",
    ],
    heat: 1,
    image: IMG.heroStreet,
    badges: ["Signature"],
    spec: { patties: 2, ozEach: 3, sear: "82s", temp: 450 },
  },
  {
    id: "spicy-ultimate",
    name: "Spicy Ultimate Smash",
    category: "smash",
    price: 1250,
    blurb: "Sriracha mayo, shaved onion, jalapeños stacked past the point of reason.",
    build: [
      "Potato roll crown",
      "Sriracha mayo",
      "Pickled jalapeños",
      "Sharp American",
      "Smashed 3oz patty",
      "Shaved onion",
      "Potato roll heel",
    ],
    heat: 4,
    image: IMG.smashSpicy,
    badges: ["Hot"],
    spec: { patties: 1, ozEach: 3, sear: "74s", temp: 460 },
  },
  {
    id: "classic-single",
    name: "The OG Smash",
    category: "smash",
    price: 995,
    blurb: "One patty, all crust, dressed the way the counter dresses it. Proof that restraint is a flavour.",
    build: [
      "Toasted potato crown",
      "Raw shaved white onion",
      "Dill pickle chips",
      "Yellow mustard",
      "Ketchup",
      "Sharp American",
      "Smashed 3oz patty",
      "Toasted potato heel",
    ],
    heat: 0,
    image: IMG.smashOg,
    spec: { patties: 1, ozEach: 3, sear: "70s", temp: 450 },
  },
  {
    id: "oklahoma",
    name: "The Oklahoma",
    category: "smash",
    price: 1295,
    blurb: "A fistful of shaved onion pressed into the raw beef. Ninety years old and still undefeated.",
    build: [
      "Steamed potato crown",
      "Yellow mustard",
      "Dill chips",
      "Sharp American",
      "Onion-smashed 3oz patty",
      "Onion-smashed 3oz patty",
      "Steamed heel",
    ],
    heat: 1,
    image: IMG.smashOklahoma,
    badges: ["Cult"],
    spec: { patties: 2, ozEach: 3, sear: "95s", temp: 440 },
  },
  {
    id: "bacon-crust",
    name: "Bacon Crust Smash",
    category: "smash",
    price: 1550,
    blurb: "Bacon ground into the patty, then more bacon on top. We regret nothing.",
    build: [
      "Toasted brioche crown",
      "Smoked aioli",
      "Thick-cut bacon",
      "Aged cheddar",
      "Bacon-ground 3oz patty",
      "Bacon-ground 3oz patty",
      "Buttered heel",
    ],
    heat: 1,
    image: IMG.baconBlack,
    spec: { patties: 2, ozEach: 3, sear: "88s", temp: 450 },
  },
  {
    id: "bacon-jam",
    name: "The Bacon Jam",
    category: "smash",
    price: 1650,
    blurb: "Bacon jam, crispy fried onions and pickled jalapeños stacked over a double. It arrives leaning and nobody minds.",
    build: [
      "Toasted brioche crown",
      "Crispy fried onions",
      "Pickled jalapeños",
      "Bacon jam",
      "Sharp American",
      "Smashed 3oz patty",
      "Sharp American",
      "Smashed 3oz patty",
      "Vine tomato",
      "Shredded romaine",
      "Buttered heel",
    ],
    heat: 3,
    image: IMG.baconJam,
    badges: ["Loaded"],
    spec: { patties: 2, ozEach: 3, sear: "88s", temp: 450 },
  },
  {
    id: "hangover",
    name: "The Hangover",
    category: "smash",
    price: 1595,
    blurb: "Hash brown, thick bacon and a fried egg with the yolk left loose. Ordered at 11am by people who need it.",
    build: [
      "Toasted brioche crown",
      "Fried egg, runny",
      "Griddled hash brown",
      "Thick-cut bacon",
      "Sharp American",
      "Smashed 3oz patty",
      "Buttered heel",
    ],
    heat: 0,
    badges: ["Runny yolk"],
    spec: { patties: 1, ozEach: 3, sear: "76s", temp: 450 },
  },
  {
    id: "smoke-show",
    name: "Smoke Show",
    category: "smash",
    price: 1495,
    blurb: "Chipotle, pepper jack, charred serrano. The only burger with a waiver.",
    build: [
      "Toasted brioche crown",
      "Chipotle crema",
      "Charred serrano",
      "Pepper jack",
      "Smashed 3oz patty",
      "Smashed 3oz patty",
      "Crispy shallot",
      "Buttered heel",
    ],
    heat: 5,
    image: IMG.stackedDark,
    badges: ["Five alarm"],
    spec: { patties: 2, ozEach: 3, sear: "84s", temp: 470 },
  },
  {
    id: "char-blue",
    name: "Char & Blue",
    category: "smash",
    price: 1595,
    blurb: "Point Reyes blue, bourbon onions, black pepper you can hear.",
    build: [
      "Toasted brioche crown",
      "Bourbon onion jam",
      "Point Reyes blue",
      "Smashed 3oz patty",
      "Smashed 3oz patty",
      "Cracked black pepper",
      "Buttered heel",
    ],
    heat: 2,
    image: IMG.eggSmash,
    spec: { patties: 2, ozEach: 3, sear: "86s", temp: 455 },
  },
  {
    id: "triple-threat",
    name: "The Triple Threat",
    category: "smash",
    price: 1895,
    blurb: "Three patties, three slices, one decision you will defend for years.",
    build: [
      "Toasted brioche crown",
      "Handcraft sauce",
      "Sharp American",
      "Smashed 3oz patty",
      "Sharp American",
      "Smashed 3oz patty",
      "Sharp American",
      "Smashed 3oz patty",
      "Buttered heel",
    ],
    heat: 1,
    image: IMG.griddleDuo,
    badges: ["Big"],
    spec: { patties: 3, ozEach: 3, sear: "104s", temp: 450 },
  },
  {
    id: "green-chile",
    name: "Green Chile Smash",
    category: "smash",
    price: 1450,
    blurb: "Hatch chiles roasted in-house every Tuesday, whether you order it or not.",
    build: [
      "Toasted brioche crown",
      "Roasted Hatch chile",
      "Monterey jack",
      "Smashed 3oz patty",
      "Smashed 3oz patty",
      "Lime crema",
      "Buttered heel",
    ],
    heat: 3,
    image: IMG.monthTray,
    spec: { patties: 2, ozEach: 3, sear: "80s", temp: 450 },
  },
  {
    id: "kraut-brat",
    name: "The Kraut Brat",
    category: "dogs",
    price: 1050,
    blurb: "Split down the middle, laid face-down on the flat top, and buried in kraut and mustard on a griddled roll.",
    build: [
      "Griddled split roll",
      "Yellow mustard",
      "Braised sauerkraut",
      "Caramelised onion",
      "Split-and-griddled bratwurst",
    ],
    heat: 1,
    image: IMG.brat,
    badges: ["Counter favourite"],
    spec: { patties: 1, ozEach: 5, sear: "3m", temp: 400 },
  },
  {
    id: "crispy-bird",
    name: "Crispy Bird",
    category: "notbeef",
    price: 1395,
    blurb: "Buttermilk overnight, dredged twice, fried until it sounds like gravel.",
    build: [
      "Potato roll crown",
      "Buttermilk ranch",
      "Bread & butter pickles",
      "Double-dredged thigh",
      "Napa slaw",
      "Potato roll heel",
    ],
    heat: 2,
    image: IMG.crispyBird,
    spec: { patties: 1, ozEach: 6, sear: "6m", temp: 350 },
  },
  {
    id: "nashville-hot",
    name: "Nashville Hot Bird",
    category: "notbeef",
    price: 1450,
    blurb: "Cayenne lacquer straight out of the fryer. Milk sold separately.",
    build: [
      "Potato roll crown",
      "Comeback sauce",
      "Dill chips",
      "Cayenne-lacquered thigh",
      "Napa slaw",
      "Potato roll heel",
    ],
    heat: 5,
    image: IMG.tenders,
    badges: ["Five alarm"],
    spec: { patties: 1, ozEach: 6, sear: "6m", temp: 350 },
  },
  {
    id: "understudy",
    name: "The Understudy",
    category: "notbeef",
    price: 1350,
    blurb: "Plant-based, smashed on the same steel, crusted just as hard. No apology.",
    build: [
      "Toasted brioche crown",
      "Handcraft sauce (vegan)",
      "Vine tomato",
      "Smashed plant patty",
      "Smashed plant patty",
      "Shredded romaine",
      "Buttered heel",
    ],
    heat: 1,
    image: IMG.sliders,
    badges: ["Plant"],
    spec: { patties: 2, ozEach: 3, sear: "78s", temp: 440 },
  },
  {
    id: "griddle-tots",
    name: "Griddle Tots",
    category: "sides",
    price: 550,
    blurb: "Fried, then finished face-down on the flat top for a crust that shatters. Warm cheese sauce comes with, not extra.",
    build: ["Tots", "Griddle-pressed", "Sea salt", "Warm cheese sauce"],
    heat: 0,
    image: IMG.loadedTots,
    spec: { patties: 0, ozEach: 8, sear: "3m", temp: 375 },
  },
  {
    id: "handcraft-fries",
    name: "Fries & the Sauce Flight",
    category: "sides",
    price: 525,
    blurb: "Cut at 4pm for tomorrow, blanched, rested overnight, fried to order — and served with all six sauces, because picking one is a trap.",
    build: [
      "Idaho russet, twice fried",
      "Sea salt",
      "Six sauces, no charge",
    ],
    image: IMG.sauceFlight,
    badges: ["Six sauces"],
    heat: 0,
    spec: { patties: 0, ozEach: 7, sear: "3m", temp: 350 },
  },
  {
    id: "loaded-tots",
    name: "Loaded Tots",
    category: "sides",
    price: 950,
    blurb: "Beer cheese, burnt ends of bacon, scallion, pickled jalapeño.",
    build: ["Griddle tots", "Beer cheese", "Bacon ends", "Scallion", "Pickled jalapeño"],
    heat: 2,
    image: IMG.basketCombo,
    spec: { patties: 0, ozEach: 12, sear: "3m", temp: 375 },
  },
  {
    id: "onion-frizzles",
    name: "Onion Frizzles",
    category: "sides",
    price: 600,
    blurb: "Shaved so thin they go translucent. Buttermilk, rice flour, gone in a minute.",
    build: ["Shaved Vidalia", "Buttermilk soak", "Rice flour"],
    heat: 0,
    image: IMG.baconLight,
    spec: { patties: 0, ozEach: 5, sear: "90s", temp: 365 },
  },
  {
    id: "burnt-sugar-shake",
    name: "Burnt Sugar Shake",
    category: "shakes",
    price: 800,
    blurb: "Caramel taken one shade past comfortable, spun with frozen custard.",
    build: ["Frozen custard", "Burnt caramel", "Maldon"],
    heat: 0,
    image: IMG.shakeSplash,
    badges: ["Spun thick"],
    spec: { patties: 0, ozEach: 16, sear: "45s", temp: 18 },
  },
  {
    id: "malt-chocolate",
    name: "Malted Chocolate",
    category: "shakes",
    price: 800,
    blurb: "Valrhona, malt powder, and enough structural integrity to hold a spoon upright.",
    build: ["Frozen custard", "Valrhona", "Malt"],
    heat: 0,
    image: IMG.shakeStack,
    spec: { patties: 0, ozEach: 16, sear: "45s", temp: 18 },
  },
  {
    id: "house-lager",
    name: "House Lager",
    category: "brew",
    price: 700,
    blurb: "Brewed for us in Brooklyn. Cold, clean, built to reset your palate.",
    build: ["4.6% ABV", "Brooklyn", "16oz pour"],
    heat: 0,
    image: IMG.burgerBrew,
    spec: { patties: 0, ozEach: 16, sear: "0s", temp: 36 },
  },
  {
    id: "rotating-ipa",
    name: "Rotating IPA",
    category: "brew",
    price: 900,
    blurb: "Whatever the cellar says is drinking best today. Ask the counter.",
    build: ["6.2–7.4% ABV", "Rotating", "16oz pour"],
    heat: 0,
    image: IMG.beerPair,
    spec: { patties: 0, ozEach: 16, sear: "0s", temp: 38 },
  },
];

export const BY_ID = Object.fromEntries(MENU.map((m) => [m.id, m])) as Record<string, MenuItem>;

/** Rotating spotlight — the burger of the month and what to drink with it. */
export const SPOTLIGHT = {
  month: "This Month",
  name: "The Oklahoma",
  itemId: "oklahoma",
  story:
    "Depression-era Oklahoma stretched scarce beef with a fistful of shaved onion pressed straight into the raw patty. On a 440° flat top the onion caramelises into the crust instead of sitting on top of it. We smash it the same way, on the same steel, every day until the onions run out.",
  pairing: {
    name: "House Lager",
    note: "Brooklyn-brewed, 4.6%. Sweet onion needs something dry and cold to argue with.",
  },
  /** A dollar off every burger of the month goes to a rotating local cause. */
  cause: {
    name: "City Meals on Wheels",
    line: "$1 from every burger supports this month's cause",
  },
};

/** What to drink with what, for the brew band. */
export const PAIRINGS = [
  {
    burgerId: "handcraft-double",
    beer: "The Wave IPA",
    note: "Citrus and pine cut straight through two patties of melted American.",
  },
  {
    burgerId: "oklahoma",
    beer: "House Lager",
    note: "Sweet caramelised onion needs something dry and very cold to argue with.",
  },
  {
    burgerId: "smoke-show",
    beer: "Amber Ale",
    note: "Malt sweetness is the only thing that talks the chipotle down.",
  },
];
